### PR TITLE
Add ability to update device IP address

### PR DESCRIPTION
**Pull request by andriichuk**
Hi! It is undocumented feature but you can update your device IP address (only on update action, on create it is not allowed).

### CODE REVIEW

**Comment by norkunas** [comment]
Hi, where did you find it? :)

**Comment by andriichuk** [comment]
> Hi, where did you find it? :)

In conversation with support system

**Comment by andriichuk** [comment]
Maybe they describe it in future

**Review by norkunas — APPROVED** [review]

**Comment by norkunas** [comment]
Thank you @andriichuk :)

**Pull request merged**
