### PR TITLE
Implement 'Edit tags with external user id' API endpoint

### PR DESCRIPTION
**Pull request by andriichuk**
Hi! I have implemented `Edit tags with external user id` API endpoint!

Closes: https://github.com/norkunas/onesignal-php-api/issues/139

### CODE REVIEW

**Comment by norkunas** [comment]
Nice, thanks! could you rebase and squash your commits? :)

**Comment by andriichuk** [comment]
@norkunas Squashed into one commit

**Comment by norkunas** [comment]
> @norkunas Squashed into one commit

:+1: but GH still shows `This branch is out-of-date with the base branch` :)

**Comment by norkunas** [comment]
could you get rid of the merge commit? :)

**Comment by andriichuk** [comment]
Found out how to update fork master branch :smile:

**Comment by norkunas** [comment]
> Found out how to update fork master branch

Perfect! :)

**Review by norkunas — APPROVED** [review]

**Comment by norkunas** [comment]
Thank you @andriichuk !

**Pull request merged**
