### PR TITLE
Add email notification parameters on resolver

### PR DESCRIPTION
**Pull request by Losams**
Add email notification support var required

### CODE REVIEW

**Comment by norkunas** [comment]
Thank you for PR.

I see that there are more options related with email: `email, `email_from_name, email_from_address`.
Could you also include them?

Also these needs to be included in tests.

**Comment by Losams** [comment]
I add optionnal datas for notification email

**Comment by norkunas** [comment]
Thank you @Losams

**Comment by Losams** [comment]
Thanks, sorry for that much back and forth :)

**Pull request merged**
