### PR TITLE
Add include_subscription_ids support to NotificationResolver.php

### PR DESCRIPTION
**Pull request by metaseller**
Parameter include_player_ids is deprecated now for create notification (see https://documentation.onesignal.com/reference/create-notification#send-to-specific-devices). 

It replaced by include_subscription_ids

### CODE REVIEW

**Comment by norkunas** [comment]
Thanks, can you run cs-fixer?

**Comment by metaseller** [comment]
> Thanks, can you run cs-fixer?

`./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.dist.php`

Like this ? Sure

**Comment by metaseller** [comment]
auto cs-fixer removes "empty" phpDocs with {@inheritdoc} and conflicts with php stan. I make some manual phpDoc changes to pass all checks

**Comment by norkunas** [comment]
> auto cs-fixer removes "empty" phpDocs with {@inheritdoc} and conflicts with php stan.

For this reason I use [no_superfluous_phpdoc_tags](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/phpdoc/no_superfluous_phpdoc_tags.rst) rule in projects, but okay as is. Thank you!

**Review by norkunas — APPROVED** [review]

**Pull request merged**
