### PR TITLE
added missing 'android_gcm_sender_id' field

### PR DESCRIPTION
**Pull request by rcerljenko**
Missing field for creating/updating app config:
android_gcm_sender_id - (string) Your Google Project number. Also know as Sender ID.

### CODE REVIEW

**Comment by norkunas** [comment]
Thanks, are you willing to add this option to tests?

**Comment by rcerljenko** [comment]
Just did.  :)

________________________________

**Comment by norkunas** [comment]
Thanks, just a little problem that your indentation is wrong because you've used tabs instead of spaces, I will fix the style ci configuration so it will properly check another time, but now could you fix that manually?

**Comment by rcerljenko** [comment]
Ok. Fixed.

________________________________

**Comment by norkunas** [comment]
Thank you @rcerljenko !

**Pull request merged**
