### PR TITLE
add status code to response content of send request method

### PR DESCRIPTION
**Pull request by tcousin-ext**
Hello @norkunas, I added the http status code in the sendRequest method for better handle of the api responses. Thank you  :)

### CODE REVIEW

**Comment by norkunas** [comment]
Hello, thank you for your contribution.

I'm not sure that this would be the right way to expose status code. Because if OneSignal would return that field with some other data then you'd have dead code.

**Comment by tcousin-ext** [comment]
Hi @norkunas, thank you for your answer. 

I can rename the key to  'http-code' or something more specific to prevent loosing data. 
What do you think ?

**Comment by norkunas** [comment]
Maybe `_status_code` would be good then. But why not just check if there is `errors` set and then assume that request failed?

**Comment by tcousin-ext** [comment]
Hi @norkunas it appears that the validation is blocked by php cs fixer and/or phpstan. Do you have any infos about that ?
Thank you in advance

**Comment by tcousin-ext** [comment]
Hi again @norkunas, can you approve the merge ? Thank you in advance

**Comment by norkunas** [comment]
Hey, you didn't answer my one question yet :) also please squash your commits

**Comment by tcousin-ext** [comment]
Sorry, it slipped my mind. We need to call many onesignal apps and we want to retrieve the error status to analyze the cause of failure more easily

**Comment by norkunas** [comment]
> Sorry, it slipped my mind. We need to call many onesignal apps and we want to retrieve the error status to analyze the cause of failure more easily

All right, so please squash your commits and I'll merge :wink:

**Comment by tcousin-ext** [comment]
Hello @norkunas i hope you're doing ok :) Is my MR ready to be approved ? Thank you

**Comment by norkunas** [comment]
Hi, you still got a merge commit, which should not be there :)

**Comment by tcousin-ext** [comment]
It should be ok now ;)

**Comment by norkunas** [comment]
Thank you

**Pull request merged**
