### PR TITLE
added firefox_icon to allowed notification fields

### PR DESCRIPTION
**Pull request by prymas007**

### CODE REVIEW

**Comment by prymas007** [comment]
resolves https://github.com/norkunas/onesignal-php-api/issues/23

**Comment by norkunas** [comment]
Thank you @prymas007

**Comment by prymas007** [comment]
np, when do you expect new release?

**Comment by norkunas** [comment]
I can release now RC2 if you need, or just use currently dev-master

**Comment by prymas007** [comment]
RC2 would be great

**Comment by prymas007** [comment]
thank you

**Pull request merged**
