### PR TITLE
Add channel_for_external_user_ids option in NotificationResolver.

### LINKED ISSUE #143: channel_for_external_user_ids is not defined
Hello,

When you use `$oneSignal->notifications()->add()` method, and the option `include_external_user_ids` you have to add the `channel_for_external_user_ids` option to specify which platform you want to target : "push" or "email". You can [see the documentation here](https://documentation.onesignal.com/reference/create-notification#platform-to-deliver-to).

But there is a problem here. If you try to use the `channel_for_external_user_ids`, an exception occurred : 
```
Symfony \ Component \ OptionsResolver \ Exception \ UndefinedOptionsException
The option "channel_for_external_user_ids" does not exist. Defined options are: (...)
```

Here is the code I use : 
```php
$config = new OneSignalConfig(env('ONESIGNAL_APP_ID'), env('ONESIGNAL_REST_API_KEY'));
$httpClient = new Psr18Client();
$requestFactory = $streamFactory = new Psr17Factory();

$oneSignal = new OneSignal($config, $httpClient, $requestFactory, $streamFactory);

$oneSignal->notifications()->add([
    'contents' => [
        'en' => $fields->notification_content,
        'fr' => $fields->notification_content,
    ],
    'headings' => [
        'en' => $fields->notification_title,
        'fr' => $fields->notification_title,
    ],
    'included_segments' => $included_segments,
    'include_external_user_ids' => $users->toArray(),
    'channel_for_external_user_ids' => 'push',
]);
```

How to make the `channel_for_external_user_ids` option work ? :-)

### PR DESCRIPTION
**Pull request by bastienu**
Closes #143

### CODE REVIEW

**Comment by norkunas** [comment]
Hello, thank you. Could you also add this option to tests?

**Comment by norkunas** [comment]
@bastienu could you fix CI errors? :)

**Comment by bastienu** [comment]
Here we are, sorry ! Everything is now OK :-)

Can you merge ? :-)

**Comment by norkunas** [comment]
Yes, one more request - could you squash your commits? :)

**Comment by bastienu** [comment]
Sorry, first PR ;-)

Squash is now done !

**Review by norkunas — APPROVED** [review]

**Comment by norkunas** [comment]
Thank you @bastienu :)

**Pull request merged**
