### PR TITLE
Added missing option to AppResolver

### PR DESCRIPTION
**Pull request by tixastronauta**
This parameter is not documented yet, but it works and it was given to me by the support team.

### CODE REVIEW

**Comment by norkunas** [comment]
Cold you add it to the tests?

**Comment by tixastronauta** [comment]
> Cold you add it to the tests?

Sure! On it

**Comment by tixastronauta** [comment]
done @norkunas 🙌

**Comment by norkunas** [comment]
Thank you @tixastronauta

**Comment by rcerljenko** [comment]
> 
> 
> This parameter is not documented yet, but it works and it was given to me by the support team.

Hi. Could you explain what does that param do? Because it's not yet documented. Thx.

**Pull request merged**
